'use client';
import { useState } from 'react';
import type { FormEvent } from 'react';
import { submitContact } from '@/lib/api';
type Props = { siteSlug: string; pageKey: string; slotKey?: string };
export function ContactForm({ siteSlug, pageKey, slotKey = 'contact.contact_cta' }: Props) {
  const [status, setStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle');
  const [message, setMessage] = useState('');
  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setStatus('loading'); setMessage(''); const form = new FormData(event.currentTarget);
    try { await submitContact(siteSlug, { name: String(form.get('name') || ''), email: String(form.get('email') || ''), phone: String(form.get('phone') || ''), interest: String(form.get('interest') || ''), message: String(form.get('message') || ''), sourcePage: pageKey, sourceSection: slotKey, tracking: { visitorId: window.localStorage.getItem('LP_VISITOR_ID'), sessionId: window.localStorage.getItem('LP_SESSION_ID'), referrer: document.referrer || '', utm: Object.fromEntries(new URLSearchParams(window.location.search).entries()) } }); setStatus('success'); setMessage('Pesan berhasil dikirim. Kami akan menghubungi Anda kembali.'); event.currentTarget.reset(); } catch (error: any) { setStatus('error'); setMessage(error?.message || 'Pesan belum berhasil dikirim. Silakan coba lagi.'); }
  }
  return <form onSubmit={onSubmit} className="lp-card grid gap-4 p-5 md:p-6"><div className="grid gap-2"><label className="text-sm font-bold text-slate-700">Nama</label><input name="name" required className="rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500" placeholder="Nama Anda" /></div><div className="grid gap-4 md:grid-cols-2"><div className="grid gap-2"><label className="text-sm font-bold text-slate-700">Email</label><input name="email" type="email" className="rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500" placeholder="email@contoh.com" /></div><div className="grid gap-2"><label className="text-sm font-bold text-slate-700">Nomor HP / WhatsApp</label><input name="phone" className="rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500" placeholder="08xxxxxxxxxx" /></div></div><div className="grid gap-2"><label className="text-sm font-bold text-slate-700">Minat / Kebutuhan</label><input name="interest" className="rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500" placeholder="Contoh: konsultasi layanan" /></div><div className="grid gap-2"><label className="text-sm font-bold text-slate-700">Pesan</label><textarea name="message" required rows={5} className="rounded-2xl border border-slate-200 px-4 py-3 outline-none focus:border-blue-500" placeholder="Ceritakan kebutuhan Anda secara singkat." /></div><button disabled={status === 'loading'} className="lp-btn lp-btn-primary w-full disabled:cursor-not-allowed disabled:opacity-60">{status === 'loading' ? 'Mengirim...' : 'Kirim Pesan'}</button>{message && <p className={`rounded-2xl px-4 py-3 text-sm font-semibold ${status === 'success' ? 'bg-green-50 text-green-700' : 'bg-red-50 text-red-700'}`}>{message}</p>}</form>;
}
