import type { ReactNode } from 'react';
import type { ArticleDetailPayload, CrudItem, PublicPagePayload, PublicSection } from '@/lib/types';
import { resolveTargetHref, getSiteHref } from '@/lib/links';
import { CtaLink } from '@/components/tracking/CtaLink';
import { ContactForm } from './ContactForm';

type SectionProps = { siteSlug: string; payload: PublicPagePayload; section: PublicSection };

type SectionComponent = (props: SectionProps) => ReactNode;

function text(value: unknown, fallback = '') { return typeof value === 'string' && value.trim() ? value : fallback; }
function titleOf(item: CrudItem) { return item.title || item.name || 'Item'; }
function imageOf(item: CrudItem) { return item.imageUrl || item.coverImageUrl || null; }
function CtaButtons({ siteSlug, payload, section, secondary = true }: SectionProps & { secondary?: boolean }) {
  const content = section.content || {};
  const primaryLabel = text(content.ctaLabel, 'Hubungi Kami');
  const primaryHref = resolveTargetHref({ siteSlug, navigation: payload.navigation, content, prefix: 'cta', fallback: '/contact' });
  const secondaryLabel = text(content.secondaryCtaLabel, 'Lihat Selengkapnya');
  const secondaryHref = resolveTargetHref({ siteSlug, navigation: payload.navigation, content, prefix: 'secondaryCta', fallback: '/' });
  return <div className="mt-8 flex flex-wrap gap-3"><CtaLink href={primaryHref} label={primaryLabel} className="lp-btn lp-btn-primary" trackingKey={payload.website.trackingKey} pageKey={payload.page.pageKey} pageSlug={payload.page.slug} slotKey={section.slotKey} sectionKey={section.sectionKey} ctaKey="primary" />{secondary && secondaryLabel && <CtaLink href={secondaryHref} label={secondaryLabel} className="lp-btn lp-btn-secondary" trackingKey={payload.website.trackingKey} pageKey={payload.page.pageKey} pageSlug={payload.page.slug} slotKey={section.slotKey} sectionKey={section.sectionKey} ctaKey="secondary" />}</div>;
}
function Heading({ eyebrow, title, description, center = false }: { eyebrow?: string; title: string; description?: string; center?: boolean }) { return <div className={center ? 'mx-auto max-w-3xl text-center' : 'max-w-3xl'}>{eyebrow && <p className="lp-eyebrow">{eyebrow}</p>}<h2 className="mt-3 text-3xl font-black tracking-tight text-slate-950 md:text-5xl">{title}</h2>{description && <p className="mt-4 text-base leading-8 text-slate-600 md:text-lg">{description}</p>}</div>; }
function EmptySection({ section }: { section: PublicSection }) { return <section className="lp-section bg-slate-50"><div className="lp-container"><div className="rounded-3xl border border-dashed border-slate-300 p-8 text-center text-slate-500">Component belum tersedia: {section.component || section.slotKey}</div></div></section>; }
function HeroSection(props: SectionProps) { const c = props.section.content || {}; return <section className="overflow-hidden bg-gradient-to-br from-blue-50 via-white to-slate-50 py-20 md:py-28"><div className="lp-container grid items-center gap-12 md:grid-cols-[1.05fr_.95fr]"><div><Heading eyebrow={text(c.eyebrow, 'Company Profile')} title={text(c.title, props.payload.website.name)} description={text(c.subtitle, props.payload.businessProfile?.description || '')} /><CtaButtons {...props} /></div><div className="lp-card min-h-[320px] overflow-hidden bg-slate-100">{c.imageUrl ? <img src={c.imageUrl} alt="Hero" className="h-full min-h-[320px] w-full object-cover" /> : <div className="flex min-h-[320px] items-center justify-center bg-gradient-to-br from-blue-600 to-indigo-700 p-8 text-center text-3xl font-black text-white">{props.payload.website.name}</div>}</div></div></section>; }
function ProfileSummarySection(props: SectionProps) { const c = props.section.content || {}; return <section className="lp-section"><div className="lp-container grid items-center gap-10 md:grid-cols-2"><div>{c.imageUrl ? <img src={c.imageUrl} alt="Profil" className="lp-card aspect-[4/3] w-full object-cover" /> : <div className="lp-card flex aspect-[4/3] items-center justify-center bg-slate-50 p-8 text-center text-xl font-black text-slate-400">Profil Bisnis</div>}</div><div><Heading title={text(c.title, 'Tentang Bisnis Kami')} description={text(c.description, props.payload.businessProfile?.description || '')} /><CtaButtons {...props} secondary={false} /></div></div></section>; }
function PreviewCards({ items, type, siteSlug }: { items: CrudItem[]; type: 'services' | 'portfolios' | 'articles' | 'brands'; siteSlug: string }) { const limited = items.slice(0, 6); if (!limited.length) return <p className="rounded-3xl bg-slate-50 p-6 text-slate-500">Belum ada data yang ditampilkan.</p>; return <div className="mt-10 grid gap-5 md:grid-cols-3">{limited.map((item, index) => { const img = imageOf(item); const href = type === 'articles' && item.slug ? getSiteHref(siteSlug, `/articles/${item.slug}`) : '#'; const body = <article className="lp-card h-full overflow-hidden"><div className="aspect-[16/10] bg-slate-100">{img ? <img src={img} alt={titleOf(item)} className="h-full w-full object-cover" /> : <div className="flex h-full items-center justify-center text-sm font-bold text-slate-400">{type} #{index + 1}</div>}</div><div className="p-5"><h3 className="text-lg font-black text-slate-950">{titleOf(item)}</h3><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-600">{item.description || item.excerpt || item.quote || 'Informasi singkat akan tampil di sini.'}</p></div></article>; return type === 'articles' ? <a key={item.id || index} href={href}>{body}</a> : <div key={item.id || index}>{body}</div>; })}</div>; }
function ServicePreviewSection(props: SectionProps) { const c = props.section.content || {}; return <section className="lp-section bg-slate-50"><div className="lp-container"><Heading title={text(c.title, 'Layanan yang Kami Tawarkan')} description={text(c.description, '')} /><PreviewCards items={props.section.data?.services || []} type="services" siteSlug={props.siteSlug} /><CtaButtons {...props} secondary={false} /></div></section>; }
function PortfolioPreviewSection(props: SectionProps) { const c = props.section.content || {}; return <section className="lp-section"><div className="lp-container"><Heading title={text(c.title, 'Portofolio Pilihan')} description={text(c.description, '')} /><PreviewCards items={props.section.data?.portfolios || []} type="portfolios" siteSlug={props.siteSlug} /><CtaButtons {...props} secondary={false} /></div></section>; }
function TrustProofSection(props: SectionProps) { const c = props.section.content || {}; const testimonials = props.section.data?.testimonials || []; const brands = props.section.data?.brands || []; return <section className="lp-section bg-slate-950 text-white"><div className="lp-container"><div className="grid gap-10 md:grid-cols-[.9fr_1.1fr]"><div><p className="lp-eyebrow text-blue-300">Trust Proof</p><h2 className="mt-3 text-3xl font-black md:text-5xl">{text(c.title, 'Dipercaya untuk Kebutuhan Bisnis')}</h2><p className="mt-4 leading-8 text-slate-300">{text(c.description, '')}</p><div className="mt-8 grid grid-cols-3 gap-3">{[1,2,3].map((n) => <div key={n} className="rounded-3xl bg-white/10 p-4"><div className="text-2xl font-black">{c[`metric${['','One','Two','Three'][n]}Value`] || '-'}</div><div className="mt-1 text-xs text-slate-300">{c[`metric${['','One','Two','Three'][n]}Label`] || 'Metric'}</div></div>)}</div></div><div className="grid gap-4">{testimonials.slice(0,2).map((item, i) => <blockquote key={item.id || i} className="rounded-3xl bg-white p-6 text-slate-950"><p className="text-lg font-bold">“{item.quote || item.description || 'Testimonial client akan tampil di sini.'}”</p><footer className="mt-4 text-sm text-slate-500">{item.name} {item.company ? `— ${item.company}` : ''}</footer></blockquote>)}{brands.length > 0 && <div className="rounded-3xl bg-white/10 p-5"><p className="text-sm font-bold text-slate-300">Partner / Brand</p><div className="mt-3 flex flex-wrap gap-2">{brands.slice(0,6).map((brand, i) => <span key={brand.id || i} className="rounded-full bg-white px-3 py-1 text-sm font-bold text-slate-800">{brand.name}</span>)}</div></div>}</div></div></div></section>; }
function CtaContactSection(props: SectionProps) { const c = props.section.content || {}; return <section className="lp-section"><div className="lp-container"><div className="rounded-[32px] bg-blue-600 p-8 text-white md:p-12"><Heading title={text(c.title, 'Siap Mendiskusikan Kebutuhan Anda?')} description={text(c.description, '')} /><CtaButtons {...props} secondary={false} /></div></div></section>; }
function TextImageSection(props: SectionProps) { const c = props.section.content || {}; return <section className="lp-section"><div className="lp-container grid items-center gap-10 md:grid-cols-2"><div><Heading title={text(c.title || c.visionTitle, props.section.slotLabel || 'Section')} description={text(c.description || c.vision || c.mission, '')} /></div><div className="lp-card bg-slate-50 p-8"><p className="text-lg leading-8 text-slate-600">{text(c.valueOne || c.stepOne || c.benefitOne || c.missionTitle, 'Konten pendukung akan tampil di sini.')}</p><p className="mt-3 text-lg leading-8 text-slate-600">{text(c.valueTwo || c.stepTwo || c.benefitTwo || c.mission, '')}</p><p className="mt-3 text-lg leading-8 text-slate-600">{text(c.valueThree || c.stepThree || c.benefitThree, '')}</p></div></div></section>; }
function PageHeroSection(props: SectionProps) { const c = props.section.content || {}; return <section className="bg-slate-50 py-16 md:py-24"><div className="lp-container"><Heading center title={text(c.title, props.payload.page.navLabel || props.payload.page.title || 'Halaman')} description={text(c.description, props.payload.page.purpose || '')} /></div></section>; }
function ServiceGridSection(props: SectionProps) { const c = props.section.content || {}; return <section className="lp-section"><div className="lp-container"><Heading title={text(c.title, 'Daftar Layanan')} description={text(c.description, '')} /><PreviewCards items={props.section.data?.services || []} type="services" siteSlug={props.siteSlug} /></div></section>; }
function PortfolioGridSection(props: SectionProps) { const c = props.section.content || {}; return <section className="lp-section"><div className="lp-container"><Heading title={text(c.title, 'Daftar Portofolio')} description={text(c.description, '')} /><PreviewCards items={props.section.data?.portfolios || []} type="portfolios" siteSlug={props.siteSlug} /></div></section>; }
function ArticlePreviewSection(props: SectionProps) { const c = props.section.content || {}; return <section className="lp-section"><div className="lp-container"><Heading title={text(c.title, 'Daftar Artikel')} description={text(c.description, '')} /><PreviewCards items={props.section.data?.articles || []} type="articles" siteSlug={props.siteSlug} /></div></section>; }
function FeaturedArticleSection(props: SectionProps) { const article = (props.section.data?.articles || [])[0]; const c = props.section.content || {}; return <section className="lp-section bg-slate-50"><div className="lp-container"><Heading title={text(c.title, 'Artikel Pilihan')} description={text(c.description, '')} />{article ? <a href={getSiteHref(props.siteSlug, `/articles/${article.slug}`)} className="mt-10 block"><article className="lp-card grid overflow-hidden md:grid-cols-[.9fr_1.1fr]"><div className="bg-slate-100">{imageOf(article) ? <img src={imageOf(article)!} alt={titleOf(article)} className="h-full min-h-[260px] w-full object-cover" /> : null}</div><div className="p-8"><h3 className="text-2xl font-black">{titleOf(article)}</h3><p className="mt-3 leading-7 text-slate-600">{article.excerpt || article.description}</p></div></article></a> : <p className="mt-8 rounded-3xl bg-white p-6 text-slate-500">Belum ada artikel published.</p>}</div></section>; }
function ArticleDetailHeroSection(props: SectionProps) { const article = props.section.data?.article; return <section className="bg-slate-50 py-16 md:py-24"><div className="lp-container max-w-4xl"><p className="lp-eyebrow">Artikel</p><h1 className="mt-4 text-4xl font-black tracking-tight md:text-6xl">{article?.title || props.payload.seo?.title || 'Detail Artikel'}</h1>{article?.excerpt && <p className="mt-5 text-lg leading-8 text-slate-600">{article.excerpt}</p>}{article?.coverImageUrl && <img src={article.coverImageUrl} alt={article.title} className="mt-10 aspect-[16/8] w-full rounded-[32px] object-cover" />}</div></section>; }
function ArticleContentSection(props: SectionProps) { const article = props.section.data?.article; return <section className="lp-section"><article className="lp-container max-w-3xl prose-lite text-slate-700 whitespace-pre-line">{article?.content || 'Konten artikel belum tersedia.'}</article></section>; }
function RelatedArticlesSection(props: SectionProps) { const c = props.section.content || {}; return <section className="lp-section bg-slate-50"><div className="lp-container"><Heading title={text(c.title, 'Artikel Terkait')} description={text(c.description, '')} /><PreviewCards items={props.section.data?.relatedArticles || props.section.data?.articles || []} type="articles" siteSlug={props.siteSlug} /></div></section>; }
function ArticleCtaSection(props: SectionProps) { return <CtaContactSection {...props} />; }
function ContactInformationSection(props: SectionProps) { const bp = props.payload.businessProfile || {}; const c = props.section.content || {}; return <section className="lp-section"><div className="lp-container grid gap-8 md:grid-cols-2"><div><Heading title={text(c.title, 'Informasi Kontak')} description={text(c.description, '')} /><div className="mt-8 grid gap-3 text-slate-700">{bp.whatsapp && <p><b>WhatsApp:</b> {bp.whatsapp}</p>}{bp.email && <p><b>Email:</b> {bp.email}</p>}{bp.address && <p><b>Alamat:</b> {bp.address}</p>}</div></div><ContactForm siteSlug={props.siteSlug} pageKey={props.payload.page.pageKey} slotKey={props.section.slotKey} /></div></section>; }
function MapsLocationSection(props: SectionProps) { const c = props.section.content || {}; return <section className="lp-section bg-slate-50"><div className="lp-container"><Heading title={text(c.title, 'Lokasi Kami')} description={text(c.description, '')} />{c.mapEmbedUrl ? <iframe src={c.mapEmbedUrl} className="mt-8 h-[360px] w-full rounded-[32px] border-0" loading="lazy" /> : <div className="mt-8 rounded-[32px] border border-dashed border-slate-300 p-12 text-center text-slate-500">Embed Google Maps belum diisi.</div>}</div></section>; }
function ContactCtaSection(props: SectionProps) { const c = props.section.content || {}; return <section className="lp-section"><div className="lp-container"><div className="grid gap-8 md:grid-cols-2"><div><Heading title={text(c.title, 'Kirim Kebutuhan Anda Sekarang')} description={text(c.description, '')} /></div><ContactForm siteSlug={props.siteSlug} pageKey={props.payload.page.pageKey} slotKey={props.section.slotKey} /></div></div></section>; }
const registry: Record<string, SectionComponent> = {
  HeroSection,
  ProfileSummarySection,
  ServicePreviewSection,
  PortfolioPreviewSection,
  TrustProofSection,
  CtaContactSection,
  OrganizationProfileSection: TextImageSection,
  HistoryTimelineSection: TextImageSection,
  VisionMissionSection: TextImageSection,
  ValueStatementSection: TextImageSection,
  TeamHighlightSection: TextImageSection,
  ServiceHeroSection: PageHeroSection,
  ServiceGridSection,
  ServiceProcessSection: TextImageSection,
  ServiceBenefitsSection: TextImageSection,
  ServiceFaqSection: TextImageSection,
  PortfolioHeroSection: PageHeroSection,
  PortfolioCategorySection: TextImageSection,
  PortfolioGridSection,
  CaseHighlightSection: TextImageSection,
  PortfolioCtaSection: CtaContactSection,
  ArticleHeroSection: PageHeroSection,
  FeaturedArticleSection,
  ArticlePreviewSection,
  ArticleDetailHeroSection,
  ArticleContentSection,
  RelatedArticlesSection,
  ArticleCtaSection,
  ContactHeroSection: PageHeroSection,
  ContactInformationSection,
  MapsLocationSection,
  ContactFaqSection: TextImageSection,
  ContactCtaSection,
};
export function RenderSections({ siteSlug, payload }: { siteSlug: string; payload: PublicPagePayload }) {
  const sections = payload.page.sections || [];
  if (!sections.length) return <section className="lp-section"><div className="lp-container"><div className="rounded-3xl border border-dashed border-slate-300 p-10 text-center"><h1 className="text-2xl font-black">Section belum dipilih</h1><p className="mt-3 text-slate-600">Pilih template section dari dashboard agar halaman ini tampil lengkap.</p></div></div></section>;
  return <>{sections.map((section) => { const Component = section.component ? registry[section.component] : null; return Component ? <Component key={section.id || section.slotKey} siteSlug={siteSlug} payload={payload} section={section} /> : <EmptySection key={section.id || section.slotKey} section={section} />; })}</>;
}
export function RenderArticleDetail({ siteSlug, detail }: { siteSlug: string; detail: ArticleDetailPayload }) {
  const payload: PublicPagePayload = { website: detail.website, seo: detail.seo, businessProfile: detail.businessProfile, navigation: detail.navigation, page: { pageKey: 'article_detail', title: detail.article.title, slug: detail.article.slug, sections: [] } };
  const heroSection: PublicSection = { id: 'article-detail-hero', slotKey: 'article_detail.article_detail_hero', component: 'ArticleDetailHeroSection', content: {}, data: { article: detail.article, relatedArticles: detail.relatedArticles } };
  const contentSection: PublicSection = { id: 'article-content', slotKey: 'article_detail.article_content', component: 'ArticleContentSection', content: {}, data: { article: detail.article, relatedArticles: detail.relatedArticles } };
  const relatedSection: PublicSection = { id: 'related-articles', slotKey: 'article_detail.related_articles', component: 'RelatedArticlesSection', content: { title: 'Artikel Terkait' }, data: { article: detail.article, relatedArticles: detail.relatedArticles } };
  return <><ArticleDetailHeroSection siteSlug={siteSlug} payload={payload} section={heroSection} /><ArticleContentSection siteSlug={siteSlug} payload={payload} section={contentSection} /><RelatedArticlesSection siteSlug={siteSlug} payload={payload} section={relatedSection} /></>;
}
